name: data-migration
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  migration:
    name: Data Migration w/ Flyway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Script
        uses: actions/checkout@v2
      - name: Execute Script
        uses: joshuaavalon/flyway-action@v3.0.0
        if: github.ref == 'refs/heads/development'
        with:
          url: jdbc:postgresql://${{ secrets.CEZBEKDB_APP_HOST }}:${{ secrets.CEZBEKDB_APP_PORT }}/${{ secrets.CEZBEKDB_APP_SCHEMA }}
          user: ${{ secrets.CEZBEKDB_APP_USER }}
          password: ${{ secrets.CEZBEKDB_APP_PASSWD }}
          locations: filesystem:./migration/sql
      - run: echo 'migrate cezbek-app schema....'